# Generated by Django 5.2.17 on 2026-09-09 18:53

import django.db.models.deletion
import saas.uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contact'),
        ('saas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='saas.tenant'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='about_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='primary_color',
            field=models.CharField(default='#146b50', max_length=7),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='tagline',
            field=models.CharField(default='Find your next property', max_length=180),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='saas.tenant'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='favicon',
            field=models.ImageField(blank=True, upload_to=saas.uploads.tenant_upload_path),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='logo',
            field=models.ImageField(blank=True, upload_to=saas.uploads.tenant_upload_path),
        ),
        migrations.AddConstraint(
            model_name='sitesetting',
            constraint=models.UniqueConstraint(fields=('tenant',), name='one_site_setting_per_tenant'),
        ),
    ]
