# Generated by Django 6.0.5 on 2026-06-21 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('owner', 'Seller / Owner'), ('agent', 'Agent'), ('buyer', 'Buyer')], default='buyer', max_length=20),
        ),
    ]
