# Generated by Django 5.2.17 on 2026-09-24 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('owner', 'Subscriber'), ('agent', 'Agent'), ('buyer', 'Buyer')], default='buyer', max_length=20),
        ),
    ]
