# Generated by Django 6.0.5 on 2026-06-21 06:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_slug_blank'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=40)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('visitor_key', models.CharField(blank=True, db_index=True, max_length=96)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_logs', to='blog.blog')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['blog', 'user'], name='blog_blogvi_blog_id_595647_idx'), models.Index(fields=['blog', 'session_key'], name='blog_blogvi_blog_id_14413e_idx'), models.Index(fields=['blog', 'visitor_key'], name='blog_blogvi_blog_id_5893e0_idx')],
                'constraints': [models.UniqueConstraint(fields=('blog', 'visitor_key'), name='unique_blog_visitor_view')],
            },
        ),
    ]
