# Generated by Django 5.2.17 on 2026-09-09 18:53

import django.db.models.deletion
import saas.uploads
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blogview'),
        ('saas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='saas.tenant'),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='saas.tenant'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='featured_image',
            field=models.ImageField(upload_to=saas.uploads.tenant_upload_path),
        ),
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AddConstraint(
            model_name='blog',
            constraint=models.UniqueConstraint(fields=('tenant', 'slug'), name='blog_tenant_slug'),
        ),
        migrations.AddConstraint(
            model_name='blogcategory',
            constraint=models.UniqueConstraint(fields=('tenant', 'slug'), name='blogcategory_tenant_slug'),
        ),
    ]
