# Generated by Django 6.0.5 on 2026-06-21 05:24

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_auto_slug_blank_propertytype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
