# Generated by Django 6.0.5 on 2026-06-21 06:13

from django.conf import settings
from django.db import migrations, models


def populate_visitor_keys(apps, schema_editor):
    PropertyView = apps.get_model("properties", "PropertyView")

    for view in PropertyView.objects.filter(visitor_key=""):
        if view.user_id:
            visitor_key = f"legacy-user:{view.user_id}:{view.id}"
        elif view.session_key:
            visitor_key = f"legacy-session:{view.session_key}:{view.id}"
        else:
            visitor_key = f"legacy-view:{view.id}"

        PropertyView.objects.filter(pk=view.pk).update(
            visitor_key=visitor_key[:96]
        )


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_propertyview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='propertyview',
            name='properties__propert_30d0e5_idx',
        ),
        migrations.AddField(
            model_name='propertyview',
            name='visitor_key',
            field=models.CharField(blank=True, db_index=True, max_length=96),
        ),
        migrations.AddIndex(
            model_name='propertyview',
            index=models.Index(fields=['property', 'visitor_key'], name='properties__propert_df976d_idx'),
        ),
        migrations.RunPython(
            populate_visitor_keys,
            migrations.RunPython.noop
        ),
        migrations.AddConstraint(
            model_name='propertyview',
            constraint=models.UniqueConstraint(fields=('property', 'visitor_key'), name='unique_property_visitor_view'),
        ),
    ]
