# Generated by Django 5.2.17 on 2026-09-09 18:53

import django.db.models.deletion
import saas.uploads
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_auto_slug_blank'),
        ('properties', '0008_property_more_area_units'),
        ('saas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='amenity',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='saas.tenant'),
        ),
        migrations.AddField(
            model_name='property',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='saas.tenant'),
        ),
        migrations.AddField(
            model_name='propertytype',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='saas.tenant'),
        ),
        migrations.AlterField(
            model_name='property',
            name='featured_image',
            field=models.ImageField(upload_to=saas.uploads.tenant_upload_path),
        ),
        migrations.AlterField(
            model_name='property',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='propertygallery',
            name='image',
            field=models.ImageField(upload_to=saas.uploads.tenant_upload_path),
        ),
        migrations.AlterField(
            model_name='propertytype',
            name='image',
            field=models.ImageField(blank=True, upload_to=saas.uploads.tenant_upload_path),
        ),
        migrations.AlterField(
            model_name='propertytype',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AddConstraint(
            model_name='property',
            constraint=models.UniqueConstraint(fields=('tenant', 'slug'), name='property_tenant_slug'),
        ),
        migrations.AddConstraint(
            model_name='propertytype',
            constraint=models.UniqueConstraint(fields=('tenant', 'slug'), name='propertytype_tenant_slug'),
        ),
    ]
