# Generated by Django 5.2.17 on 2026-09-14 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_city_tenant_state_tenant_district_city_district'),
        ('properties', '0012_alter_amenity_id_alter_compareproperty_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.district'),
        ),
    ]
