# Generated by Django 5.2.17 on 2026-09-15 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0013_property_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='building_apartment',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='property',
            name='street',
            field=models.CharField(blank=True, max_length=160),
        ),
    ]
