# Generated by Codex on 2026-09-16

from django.db import migrations, models

import saas.uploads


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0015_alter_property_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="featured_image",
            field=models.ImageField(
                blank=True,
                upload_to=saas.uploads.tenant_upload_path,
            ),
        ),
    ]
