# Generated by Django 5.2.17 on 2026-09-10 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0002_backfill_brijvas'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='is_platform',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='domain',
            name='last_attempt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='domain',
            name='provisioning_requested',
            field=models.BooleanField(default=False),
        ),
    ]
