# Generated by Django 5.2.17 on 2026-09-15 04:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0007_pendingsignup_usertype_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='discount_percent',
            field=models.PositiveIntegerField(default=0, help_text='Percentage discount applied at checkout.', validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
