# Generated by Django 5.2.17 on 2026-09-15 04:30

import django.core.validators
from django.db import migrations, models


def seed_billing_snapshots(apps, schema_editor):
    BillingSetting = apps.get_model('saas', 'BillingSetting')
    BillingOrder = apps.get_model('saas', 'BillingOrder')
    PendingSignup = apps.get_model('saas', 'PendingSignup')
    BillingSetting.objects.get_or_create(pk=1, defaults={'gst_percent': 18, 'business_name': 'Vistaflo'})
    for model in (BillingOrder, PendingSignup):
        for item in model.objects.all():
            if not item.subtotal_amount:
                item.subtotal_amount = item.amount
            if not item.taxable_amount:
                item.taxable_amount = item.amount
            item.save(update_fields=['subtotal_amount', 'taxable_amount'])


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0008_plan_discount_percent'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gst_percent', models.PositiveIntegerField(default=18, validators=[django.core.validators.MaxValueValidator(100)])),
                ('business_name', models.CharField(default='Vistaflo', max_length=160)),
                ('business_address', models.TextField(blank=True)),
                ('gstin', models.CharField(blank=True, max_length=32)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Billing setting',
                'verbose_name_plural': 'Billing settings',
            },
        ),
        migrations.AddField(
            model_name='billingorder',
            name='discount_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='billingorder',
            name='discount_percent',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='billingorder',
            name='gst_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='billingorder',
            name='gst_percent',
            field=models.PositiveIntegerField(default=18),
        ),
        migrations.AddField(
            model_name='billingorder',
            name='subtotal_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='billingorder',
            name='taxable_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pendingsignup',
            name='discount_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pendingsignup',
            name='discount_percent',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pendingsignup',
            name='gst_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pendingsignup',
            name='gst_percent',
            field=models.PositiveIntegerField(default=18),
        ),
        migrations.AddField(
            model_name='pendingsignup',
            name='subtotal_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pendingsignup',
            name='taxable_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(seed_billing_snapshots, migrations.RunPython.noop),
    ]
