# Generated by Django 5.2.17 on 2026-09-24 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0014_billing_duration_months'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='purchaseagreementacceptance',
            new_name='saas_purcha_user_id_b0625d_idx',
            old_name='saas_purcha_user_id_a9e08f_idx',
        ),
        migrations.RenameIndex(
            model_name='purchaseagreementacceptance',
            new_name='saas_purcha_tenant__17fad5_idx',
            old_name='saas_purcha_tenant__28fb1a_idx',
        ),
        migrations.RenameIndex(
            model_name='purchaseagreementacceptance',
            new_name='saas_purcha_order_i_eafc0b_idx',
            old_name='saas_purcha_order_i_2747bd_idx',
        ),
        migrations.RenameIndex(
            model_name='purchaseagreementacceptance',
            new_name='saas_purcha_pending_3f913f_idx',
            old_name='saas_purcha_pending_69184b_idx',
        ),
    ]
